/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/labs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListLabs'];
    put?: never;
    post: operations['CreateLab'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/labs/{labId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetLab'];
    put?: never;
    post?: never;
    delete: operations['DeleteLab'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/labs/{labId}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['StartLab'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/labs/{labId}/deallocate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['DeallocateLab'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/labs/{labId}/extend-expiration': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ExtendLabExpiration'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/labs/{labId}/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListLabJobs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/labs/{labId}/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListLabAudit'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/jobs/{jobId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetJob'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/jobs/{jobId}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['CancelJob'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/environment': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetEnvironment'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/config.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetClientConfig'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuditEventDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      labId: null | string;
      /** Format: uuid */
      jobId: null | string;
      actorId: string;
      action: string;
      detail: null | string;
      correlationId: string;
      /** Format: date-time */
      occurredAt: string;
    };
    ClientConfigDto: {
      authMode: string;
      tenantId: null | string;
      clientId: null | string;
      authority: null | string;
      apiScope: null | string;
    };
    CreateLabRequest: {
      name: string;
      region: string;
      /** Format: int32 */
      ttlHours: number;
    };
    CreateLabResponse: {
      lab: components['schemas']['LabDto'];
      job: components['schemas']['JobDto'];
    };
    DeleteLabRequest: {
      confirmName: string;
    };
    EnvironmentDto: {
      infrastructureMode: string;
      isSimulated: boolean;
      authenticationMode: string;
      regions: string[];
      /** Format: int32 */
      minTtlHours: number;
      /** Format: int32 */
      maxTtlHours: number;
      /** Format: int32 */
      maxExtensionHours: number;
      /** Format: int32 */
      maxActiveLabsPerUser: number;
    };
    /** @enum {unknown} */
    ErrorCategory:
      'Transient' | 'Permanent' | 'Authorization' | 'Quota' | 'Validation' | 'Cancellation' | null;
    ExtendExpirationRequest: {
      /** Format: int32 */
      hours: number;
    };
    HttpValidationProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
      errors?: {
        [key: string]: string[];
      };
    };
    JobDto: {
      /** Format: uuid */
      jobId: string;
      /** Format: uuid */
      labId: string;
      type: components['schemas']['LabJobType'];
      status: components['schemas']['LabJobStatus'];
      /** Format: int32 */
      progress: number;
      currentStep: null | string;
      /** Format: int32 */
      attemptCount: number;
      /** Format: int32 */
      maxAttempts: number;
      requestedBy: string;
      /** Format: date-time */
      requestedAt: string;
      /** Format: date-time */
      startedAt: null | string;
      /** Format: date-time */
      completedAt: null | string;
      /** Format: date-time */
      updatedAt: string;
      cancelRequested: boolean;
      errorCategory: null | components['schemas']['ErrorCategory'];
      errorCode: null | string;
      errorMessage: null | string;
      statusUrl: string;
    };
    /** @enum {unknown} */
    LabCommand: 'Start' | 'Deallocate' | 'Delete' | 'ExtendExpiration';
    LabDto: {
      /** Format: uuid */
      id: string;
      name: string;
      ownerId: string;
      ownerName: string;
      region: string;
      resourceGroupName: string;
      state: components['schemas']['LabState'];
      stateReason: null | string;
      powerState: components['schemas']['VmPowerState'];
      isSimulated: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      expiresAt: string;
      currentJob: null | components['schemas']['JobDto'];
      allowedActions: components['schemas']['LabCommand'][];
    };
    /** @enum {unknown} */
    LabJobStatus: 'Queued' | 'Running' | 'Succeeded' | 'Failed' | 'Cancelled';
    /** @enum {unknown} */
    LabJobType:
      | 'ProvisionLab'
      | 'StartVm'
      | 'DeallocateVm'
      | 'DeleteLab'
      | 'SeedDatabase'
      | 'ApplyIndex'
      | 'RemoveIndex'
      | 'RunIndexBenchmark'
      | 'RunDeadlock'
      | 'RunDeadlockResolution'
      | 'CollectMetrics'
      | 'CreateBackup'
      | 'VerifyBackup'
      | 'AssessPatches'
      | 'InstallPatches'
      | 'ReconcileLab';
    /** @enum {unknown} */
    LabState:
      | 'Requested'
      | 'Provisioning'
      | 'Stopped'
      | 'Starting'
      | 'Configuring'
      | 'Ready'
      | 'Deallocating'
      | 'Maintenance'
      | 'Deleting'
      | 'Deleted'
      | 'Failed';
    ProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
    };
    /** @enum {unknown} */
    VmPowerState:
      | 'Unknown'
      | 'NotCreated'
      | 'Starting'
      | 'Running'
      | 'Deallocating'
      | 'Deallocated'
      | 'Deleted';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ListLabs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabDto'][];
        };
      };
    };
  };
  CreateLab: {
    parameters: {
      query?: never;
      header?: {
        'Idempotency-Key'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLabRequest'];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateLabResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  GetLab: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabDto'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  DeleteLab: {
    parameters: {
      query?: never;
      header?: {
        'Idempotency-Key'?: string;
      };
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteLabRequest'];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobDto'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  StartLab: {
    parameters: {
      query?: never;
      header?: {
        'Idempotency-Key'?: string;
      };
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobDto'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  DeallocateLab: {
    parameters: {
      query?: never;
      header?: {
        'Idempotency-Key'?: string;
      };
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobDto'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  ExtendLabExpiration: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExtendExpirationRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabDto'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  ListLabJobs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobDto'][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  ListLabAudit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        labId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditEventDto'][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  GetJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobDto'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  CancelJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobDto'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  GetEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EnvironmentDto'];
        };
      };
    };
  };
  GetClientConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ClientConfigDto'];
        };
      };
    };
  };
}
